# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an issue or PR is considered stale
daysUntilStale: 15

# Number of days of inactivity before a stale issue or PR is closed
daysUntilClose: 30

# Issues or PRs with these labels will never be considered stale
exemptLabels:
  - up for grabs

# Label to use when marking an issue or PR as stale
staleLabel: waiting

# Comment to post when marking an issue or PR as stale
markComment: >
  Hi all! This thread has not had any recent activity.
  Are there any updates? Thanks!

# Comment to post when closing a stale issue or PR
closeComment: >
  Hi everyone.
  This thread is being closed as there was no response to the previous prompt.
  However, please leave a comment whenever you're ready to resume,
  so the thread can be reopened. Thanks again!

# Limit to only `issues` or `pulls`
only: pulls
