# mpg123

> Console MPEG Audio Player.
> More information: <https://www.mpg123.de/>.

- Play mp3 files:

`mpg123 {{path/target_file1.mp3}} {path/target_file2.mp3}}`

- Play a mp3 from stdin:

`mpg123 -`

- Interactive command  to jump forward to the next song:

`f`

- Interactive command  to jump back to the beginning for the song:

`b`

- Interactive command  to stop or replay:

`s`

- Interactive command  to fast forward:

`.`

- Interactive command  to quit:

`q`
