name: 📄 Page modification request
title: "Page modification request: "
description: Request modification of a page.
labels: page edit, help wanted
body:
  - type: textarea
    attributes:
      label: Command description
      description: Describe the command you want the page(s) to be modified.
      placeholder: Tell us about the changes in the command!
    validations:
      required: true
  - type: input
    attributes:
      label: Command details
      description: Describe any details related to a command.
      placeholder: e.g. command version
  - type: input
    attributes:
      label: Documentation
      description: Link to the official documentation.
      placeholder: https://example.com
  - type: dropdown
    attributes:
      label: Platform
      description: What platform does the program run on? (Select "Common" if the program works on more than one platform)
      options:
        - Android
        - Common
        - FreeBSD
        - Linux
        - macOS (OS X)
        - NetBSD
        - OpenBSD
        - SunOS
        - Windows
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Provide additional information if the command differs between platforms.
