name: 📄 Page request
title: "page request: "
description: Request creation of a page.
labels: new command, help wanted
body:
  - type: textarea
    attributes:
      label: Command description
      description: Describe a command you want to be summarized.
      placeholder: Tell us about the command!
    validations:
      required: true
  - type: input
    attributes:
      label: Command details
      description: Describe any details related to a command.
      placeholder: e.g. command version
  - type: input
    attributes:
      label: Documentation
      description: Link to the official documentation.
      placeholder: https://example.com
  - type: dropdown
    attributes:
      label: Platform
      description: What OS does the program run on? (Select 'Common' if the program works on more than one OS)
      options:
        - Linux
        - macOS (OS X)
        - Windows
        - FreeBSD
        - OpenBSD
        - NetBSD
        - Android
        - SunOS
        - Common
    validations:
      required: true
