name: 🐛 Bug report
title: "page fix: "
description: Bug report template
labels: bug
body:
  - type: textarea
    attributes:
      label: Command description
      description: Describe a command you want to be fixed
      placeholder: Tell us what Tl;Dr page fix you want to see!
    validations:
      required: true
  - type: input
    attributes:
      label: Command details
      description: Describe any details related to a command
      placeholder: Tell us a command version for instance
  - type: dropdown
    attributes:
      label: OS
      description: Specify an operation system this command is implemented for (if you don't know please select "Other")
      multiple: false
      options:
        - Linux
        - Mac OS
        - Windows
        - General
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: OS details
      description: Describe any details related to an operating system
      placeholder: Tell us an OS version for instance
