name: 📄 Page request
title: "page request: "
description: Page request template.
labels: new command
body:
  - type: textarea
    attributes:
      label: Command description
      description: Describe a command you want to be summarized.
      placeholder: Tell us what TLDR page you want to see!
    validations:
      required: true
  - type: input
    attributes:
      label: Command details
      description: Describe any details related to a command.
      placeholder: e.g. command version
  - type: dropdown
    attributes:
      label: OS
      description: Specify an operation system this command is implemented for (if you don't know please select "Other").
      multiple: false
      options:
        - Linux
        - macOS
        - Windows
        - General
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: OS details
      description: Describe any details related to an operating system.
      placeholder: e.g. OS version obtained via `uname -a`
