name: Check PR Description

on:
  pull_request:
    types: opened

permissions:
  pull-requests: write

jobs:
  check-pr-body:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically close modified PR templates
        uses: actions/github-script@v7
        with:
          script: |
            const requiredText1 = "The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.";
            const requiredText2 = "The page description(s) have links to documentation or a homepage.";
            const requiredText3 = "The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).";
            const requiredText4 = "The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).";
            const requiredText5 = "The PR contains at most 5 new pages.";
            const requiredText6 = "The PR is authored by me, or has been human-reviewed if it was created with AI or machine translation software.";
            const requiredText7 = "The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).";
            const body = context.payload.pull_request.body || "";

            if (!body.includes(requiredText1) || !body.includes(requiredText2) || !body.includes(requiredText3) || !body.includes(requiredText4) || !body.includes(requiredText5) || !body.includes(requiredText6) || !body.includes(requiredText7)) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: `This PR was automatically closed because the description is missing required text: \`${requiredText}\`.\n\nPlease reopen with a description that includes it.`
              });

              // Close the PR
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                state: "closed"
              });
            }
